email: "eloi.navet@u-bordeaux.fr"
start_year: 2004
end_year: 2025

brain_terms:
  - "dementia"
  - "neurodegenerative"
  - "neurodegeneration"

imaging_terms:
  - "MRI"
  - "structural MRI"
  - "magnetic resonance imaging"
  - "structural magnetic resonance imaging"
  - "sMRI"
  - "voxel-based morphometry"
  - "VBM"
  - "cortical thickness"
  - "volumetric"
  - "brain atrophy"
  - "DTI"
  - "diffusion tensor imaging"
  - "diffusion MRI"

disease_terms:
  - "Alzheimer"
  - "AD"
  - "Parkinson"
  - "PD"
  - "PDD"
  - "DLB"
  - "Lewy body dementia"
  - "LBD"
  - "frontotemporal dementia"
  - "FTD"
  - "semantic dementia"
  - "SD"
  - "primary progressive aphasia"
  - "PPA"
  - "progressive aphasia"
  - "semantic variant PPA"
  - "svPPA"
  - "non-fluent variant PPA"
  - "PNFA"
  - "behavioral variant FTD"
  - "BV"
  - "multiple system atrophy"
  - "MSA"
  - "MSA-P"
  - "MSA-C"
  - "progressive supranuclear palsy"
  - "PSP"
  - "corticobasal degeneration"
  - "CBD"
  - "corticobasal syndrome"
  - "amyotrophic lateral sclerosis"
  - "ALS"
  - "Huntington’s disease"
  - "Huntington's disease"
  - "Wilson’s disease"
  - "WD"
  - "Spinocerebellar ataxias"
  - "SCA"
  - "Friedreich’s ataxia"
  - "FA"
  - "Spinal muscular atrophy"
  - "SMA"
  - "vascular dementia"
  - "vascular cognitive impairment"
  - "VaD"
  - "CADASIL"
  - "cerebral autosomal dominant arteriopathy with subcortical infarcts and
    leukoencephalopathy"
  - "Normal pressure hydrocephalus"
  - "NPH"
  - "Creutzfeldt-Jakob disease"
  - "CJD"
  - "variant CJD"
  - "vCJD"
  - "Gerstmann-Sträussler-Scheinker syndrome"
  - "GSS"
  - "Fatal familial insomnia"
  - "FFI"
  - "Kuru"
  - "Pantothenate kinase-associated neurodegeneration"
  - "PKAN"
  - "Metachromatic leukodystrophy"
  - "MLD"
  - "Krabbe disease"
  - "Pelizaeus-Merzbacher disease"
  - "Canavan disease"
  - "Neuronal ceroid lipofuscinosis"
  - "NCL"
  - "Batten disease"
  - "Neurodegeneration with brain iron accumulation"
  - "NBIA"
  - "Beta-propeller protein-associated neurodegeneration"
  - "BPAN"
  - "HIV-associated neurocognitive disorder"
  - "HAND"
  - "AIDS dementia complex"
  - "ADC"
  - "HAD"
  - "Chronic traumatic encephalopathy"
  - "CTE"
  - "multiple sclerosis"
  - "MS"
  - "degenerative leukoencephalopathies"
  - "mild cognitive impairment"
  - "MCI"
  - "cognitive impairment"
  - "Wernicke-Korsakoff syndrome"
  - "Wernicke's encephalopathy"
  - "Korsakoff's syndrome"
  - "posterior cortical atrophy"
  - "PCA"
  - "mixed dementia"
  - "alcohol-related dementia"
  - "ARD"
  - "young onset dementia"
  - "corticobasal degeneration"
  - "multiple system atrophy"
  - "amyotrophic lateral sclerosis"
  - "HD"
  - "Spinocerebellar ataxias"
  - "spinal muscular atrophy"
  - "variant Creutzfeldt-Jakob disease"

ai_terms:
  - "artificial intelligence"
  - "machine learning"
  - "deep learning"
  - "transformer"
  - "neural network"
  - "classifier"
  - "classification"
  - "support vector machine"
  - "random forest"
  - "xgboost"

diagnostic_terms:
  - "differential"
  - "differential diagnosis"
  - "discrimination"
  - "differentiating"
  - "multi-disease classification"
  - "multiclass classification"
  - "multi-class"
  - "multiclass"
  - "multi-classification"
  - "phenotypes"
  - "subtyping"
  - "staging"
  - "variant"
